# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7680d34015e583509324d5af0733864dfde4cab5f3666bdcd805a3796b10527d0cdd5f663a97ddc4a87951bd5d7e7bad97106f089ded4f4c56c47abc52f47f85

test:
  secret_key_base: 3dcee535034c919f596b984a0268e21ce777fb535596d2d3cfe5826ee21b757a181a7ca6e4b6e02a6e593c5edbd603b4d15cd4f5136f0e752f6724855d44a671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
